#
# This file, with this flag, must be present in the default branch in
# order for the buildomat integration to create check suites.
#
enable = true
org_only = true

allow_users = [
	"oxide-reflector-bot[bot]",
	"oxide-renovate[bot]",
]
